image: termux/package-builder:latest

stages:
  - build

## Common configuration for all build jobs.
## Variables BINTRAY_* should be unset to
## prevent leaking of sensitive information.
.job_template: &build_job
  stage: build
  script:
    - unset BINTRAY_USERNAME
    - unset BINTRAY_API_KEY
    - unset BINTRAY_GPG_SUBJECT
    - unset BINTRAY_GPG_PASSPHRASE
    - |
      for package in $(./scripts/build/ci/determine_git_changes.sh); do
          ./build-package.sh -q -i -a "$TERMUX_ARCH" "$package" || exit 1
      done
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
  artifacts:
    when: always
    paths:
      - debs

## Building packages for AArch64.
build-aarch64:
  <<: *build_job
  variables:
    TERMUX_ARCH: aarch64

## Building packages for ARM.
build-arm:
  <<: *build_job
  variables:
    TERMUX_ARCH: arm

## Building packages for i686.
build-i686:
  <<: *build_job
  variables:
    TERMUX_ARCH: i686

## Building packages for x86_64.
build-x86_64:
  <<: *build_job
  variables:
    TERMUX_ARCH: x86_64

## Submit build packages to repository.
#upload-packages:
#  stage: deploy
#  only:
#    - android-7@xeffyr/termux-packages
#    - master@xeffyr/termux-packages
#  script:
#    - MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
#    - |
#      if [ -n "$MODIFIED_PACKAGES" ]; then
#          ./scripts/bintray-add-package.sh --path ./termux-packages/debs $MODIFIED_PACKAGES
#      else
#          exit 0
#      fi
#  retry:
#    max: 2
#    when:
#      - runner_system_failure
#      - unknown_failure
